### PR TITLE
Remove bogus test entries

### PR DESCRIPTION
**Pull request by jankatins**
[Done in the github editor...]

### CODE REVIEW

**Comment by ocefpaf** [comment]
@JanSchulz because you edit it from the repository, instead of a fork, it will trigger the upload.  That is OK here because the build number was not bumped, but I guess we should watch out for that when editing from GitHub directly.

**Comment by jankatins** [comment]
Ouch: Thanks for pointing that out, I never even realized that it not forked the repo. Seems that I never did that when I had some kind of access to the repo, because otherwise it forks per default......  

At least the problem on circleci was removed...

**Comment by ocefpaf** [comment]
> At least the problem on circleci was removed...

:+1: 

I am looking into a permanent solution. (Meaning adding a real test there.)

**Comment by ocefpaf** [comment]
I was thinking about a `run_test.py` with

``` python
import os
import sys

inc = os.path.join(sys.prefix, 'Library', 'include')
assert os.path.isfile(os.path.join(inc, 'stdint.h'))
assert os.path.isfile(os.path.join(inc, 'inttypes.h'))
```

But then I realized that our linter does not care for the fact that conda automatically finds the `run_test.py` (or `run_test.sh`) and runs it. We need to either relax the recipe _test field_ rule or make the linter aware of `run_test.{py,sh}` files.

**Comment by pelson** [comment]
> We need to either relax the recipe test field rule or make the linter aware of run_test.{py,sh} files

It should be relaxed, IMO.

Thanks for fixing @JanSchulz.

**Pull request merged**
